spring.application.name=novobank-account-service

# DataSource
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/novobanco}
spring.datasource.username=${DB_USERNAME:novobanco}
spring.datasource.password=${DB_PASSWORD:novobanco123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Server
server.port=${PORT:8080}
server.error.include-message=never
server.error.include-stacktrace=never
