spring.jpa.show-sql=true
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/novobanco}
spring.datasource.username=${DB_USERNAME:novobanco}
spring.datasource.password=${DB_PASSWORD:novobanco123}
