spring.jpa.show-sql=false
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.error.include-message=never
server.error.include-stacktrace=never
